### ISSUE TITLE
Upgrade Rehberi

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/docs#1]
V3 de çok fazla database ve benzeri değişikler oldu özellikle db geçirmek için bir upgrade rehberi hazırlayabilir misin?

**Comment by ayberktandogan** [comment]
Az önce güncelledim. Sayfanın birkaç dakika içinde yenilenmesi lazım. Eğer eksik veya hatalı bir yer çıkarsa, söylersen sevinirim.

**Comment by Hime-Dev** [comment]
tabi elimden geldiği kadar yardımcı olurum ek olarak haberiniz olsun v3 rehberinin en başında nodemon paketi yükletmeyi kaldırmayı unutmuşsunuz neler değişti bölümünde kaldırıldığını söylemişsiniz de
