### ISSUE TITLE
Eksik Dosyalar 

### ISSUE THREAD

**Issue by Hime-Dev** [ForFansubs/docs#2]
./src/config dosyasında bulunan drawer_items.js, footer_items.js, sss_page_text.js ve recruitment_panels.js dosyalarını her dosyada bulunan açıklamalara göre doldurun.

bu dosyalar front end'e bulunmamaktadır. Sitemi v3 geçirirken herhangi bir sorun teşkil eder mi 0 dan kuruyorum?

**Comment by ayberktandogan** [comment]
https://github.com/ForFansubs/front-end/tree/beta/src/config burada hepsi var gözüküyor. Doğru branch'i indirdiğinizden emin misiniz? Docs'da hala master'da buildleyin diye gösteriyor ancak v3 beta branchinde, master'a almadım daha.

Cloneladığınız dosya içerisinde `git checkout beta` yazarak v3'e geçebilirsiniz.

**Comment by Hime-Dev** [comment]
Tamamdır dediğiniz gibi v3 branch'nı indirip kuruyorum birde front-end .env'den discord link kaldırılmış sanırım unutulan bir şey mi nasıl algılayacak ön taraftaki discord linkini ?

**Comment by ayberktandogan** [comment]
`drawer_items.js` ya da `footer_items.js` dosyasına kendiniz ekleyebilirsiniz. `drawer_items.js`'te Discord örneği var zaten.

**Comment by Hime-Dev** [comment]
teşekkürler.
